Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebQuanLyAppOnTap.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            if (Session["fullname"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            return View();
        }
    }
}

Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using OfficeOpenXml;
using WebQuanLyAppOnTap.Models;

namespace WebQuanLyAppOnTap.Controllers
{
    public class QuestionsController : Controller
    {
        // GET: Questions
        public ActionResult Index(int? selectedQuizId)
        {
            if (Session["fullname"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            else
            {
                List<Quiz> quizList = GetQuizzesFromDatabase();
                ViewBag.Quizzes = new SelectList(quizList, "Id", "NameQuiz", selectedQuizId);

                ConnectionMySQL connection = new ConnectionMySQL();

                string query = "SELECT u.id, u.question, u.answer1, u.answer2, u.answer3, u.answer4, u.correctanswer, u.quiz_id, t.namequiz " +
                   "FROM questions u " +
                   "INNER JOIN quizzes t ON u.quiz_id = t.id";

                MySqlConnection conn = connection.ConnectionSQL();
                MySqlCommand cmd = new MySqlCommand(query, conn);

                List<Question> questionList = new List<Question>();

                try
                {
                    conn.Open();
                    using (MySqlDataReader dataReader = cmd.ExecuteReader())
                    {
                        while (dataReader.Read())
                        {
                            Question question = new Question();
                            question.Id = Convert.ToInt32(dataReader["id"]);
                            question.QuestionContent = dataReader["question"].ToString();
                            question.Answer1 = dataReader["answer1"].ToString();
                            question.Answer2 = dataReader["answer2"].ToString();
                            question.Answer3 = dataReader["answer3"].ToString();
                            question.Answer4 = dataReader["answer4"].ToString();
                            question.CorrectAnswer = dataReader["correctanswer"].ToString();
                            question.Quiz_Id = Convert.ToInt32(dataReader["quiz_id"]);
                            question.NameQuiz = dataReader["namequiz"].ToString();
                            questionList.Add(question);
                        }
                    }

                    if (selectedQuizId.HasValue)
                    {
                        questionList = questionList.Where(q => q.Quiz_Id == selectedQuizId).ToList();
                    }

                    return View(questionList);
                }
                catch (Exception ex)
                {
                    return View("Error");
                }
                finally
                {
                    conn.Close();
                }
            }
        }

        public ActionResult Create()
        {
            if (Session["fullname"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            else
            {
                List<Quiz> quizList = GetQuizzesFromDatabase();

                List<SelectListItem> subjectListItems = quizList.Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.NameQuiz
                }).ToList();

                ViewBag.Quizzes = subjectListItems;

                var defaultSubjectId = quizList.FirstOrDefault()?.Id;
                ViewBag.DefaultSubjectId = defaultSubjectId;

                return View();
            }
        }

        private List<Quiz> GetQuizzesFromDatabase()
        {
            List<Quiz> quizList = new List<Quiz>();

            try
            {
                ConnectionMySQL connection = new ConnectionMySQL();
                MySqlConnection conn = connection.ConnectionSQL();

                conn.Open();

                string query = "SELECT * FROM quizzes";

                MySqlCommand cmd = new MySqlCommand(query, conn);

                using (MySqlDataReader dataReader = cmd.ExecuteReader())
                {
                    while (dataReader.Read())
                    {
                        Quiz quiz = new Quiz();
                        quiz.Id = Convert.ToInt32(dataReader["id"]);
                        quiz.NameQuiz = dataReader["namequiz"].ToString();
                        quizList.Add(quiz);
                    }
                }
                conn.Close();
            }
            catch (Exception ex)
            {

            }

            return quizList;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                if (IsQuestionExists(question.Quiz_Id, question.QuestionContent, question.CorrectAnswer))
                {
                    ViewData["Error"] = "Câu hỏi đã tồn tại cho bài kiểm tra này!";
                    PopulateDropdownList();
                    return View(question);
                }

                ConnectionMySQL connection = new ConnectionMySQL();
                MySqlConnection conn = connection.ConnectionSQL();

                string query = "INSERT INTO questions (quiz_id, question, answer1, answer2, answer3, answer4, correctanswer) " +
                               "VALUES (@quizId, @question, @answer1, @answer2, @answer3, @answer4, @correctAnswer)";

                MySqlCommand cmd = new MySqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@quizId", question.Quiz_Id);
                cmd.Parameters.AddWithValue("@question", question.QuestionContent);
                cmd.Parameters.AddWithValue("@answer1", question.Answer1);
                cmd.Parameters.AddWithValue("@answer2", question.Answer2);
                cmd.Parameters.AddWithValue("@answer3", question.Answer3);
                cmd.Parameters.AddWithValue("@answer4", question.Answer4);
                cmd.Parameters.AddWithValue("@correctAnswer", question.CorrectAnswer);

                try
                {
                    conn.Open();
                    cmd.ExecuteNonQuery();
                }
                catch (Exception ex)
                {
                    
                }
                finally
                {
                    conn.Close();
                }

                return RedirectToAction("Index");
            }

            PopulateDropdownList();
            return View(question);
        }

        private bool IsQuestionExists(int quizId, string questionContent, string correctAnswer)
        {
            ConnectionMySQL connection = new ConnectionMySQL();
            MySqlConnection conn = connection.ConnectionSQL();

            string query = "SELECT COUNT(*) FROM questions WHERE quiz_id = @quizId AND question = @questionContent AND correctanswer = @correctAnswer";

            MySqlCommand cmd = new MySqlCommand(query, conn);
            cmd.Parameters.AddWithValue("@quizId", quizId);
            cmd.Parameters.AddWithValue("@questionContent", questionContent);
            cmd.Parameters.AddWithValue("@correctAnswer", correctAnswer);

            try
            {
                conn.Open();
                int count = Convert.ToInt32(cmd.ExecuteScalar());

                return count > 0;
            }
            catch (Exception ex)
            {
                return false;
            }
            finally
            {
                conn.Close();
            }
        }

        private void PopulateDropdownList()
        {
            List<Quiz> quizList = GetQuizzesFromDatabase();
            List<SelectListItem> subjectListItems = quizList.Select(s => new SelectListItem
            {
                Value = s.Id.ToString(),
                Text = s.NameQuiz
            }).ToList();

            ViewBag.Quizzes = subjectListItems;

            var defaultSubjectId = quizList.FirstOrDefault()?.Id;
            ViewBag.DefaultSubjectId = defaultSubjectId;
        }

        public ActionResult CreateList()
        {
            if (Session["fullname"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            else
            {
                List<Quiz> quizList = GetQuizzesFromDatabase();

                List<SelectListItem> subjectListItems = quizList.Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.NameQuiz
                }).ToList();

                ViewBag.Quizzes = subjectListItems;

                var defaultSubjectId = quizList.FirstOrDefault()?.Id;
                ViewBag.DefaultSubjectId = defaultSubjectId;

                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> UploadQuestions(HttpPostedFileBase file, int quiz_Id)
        {
            if (file != null && file.ContentLength > 0)
            {
                if (Path.GetExtension(file.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
                {
                    // Đọc câu hỏi từ Excel
                    List<Question> questions = await ReadQuestionsFromExcel(file.InputStream, quiz_Id);

                    if (questions.Count == 0)
                    {
                        TempData["QuestionExistsError"] = "Bai kiem tra da ton tai cau hoi trong file Excel!";
                        return RedirectToAction("CreateList");
                    }

                    SaveQuestionsToDatabase(questions, quiz_Id);
                }
            }

            return RedirectToAction("Index");
        }

        private async Task<List<Question>> ReadQuestionsFromExcel(Stream inputStream, int quizId)
        {
            List<Question> questions = new List<Question>();

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel='shortcut icon' href='~/Content/images/hutechlogo.png' />

    <style>
        .nav-item p {
            color: black;
        }

        .collapsed .main-sidebar {
            width: 50px; /* hoặc bất kỳ kích thước nào bạn muốn khi thu nhỏ */
        }

        .expanded .main-sidebar {
            width: 250px; /* hoặc bất kỳ kích thước nào bạn muốn khi mở rộng */
        }

        .main-sidebar {
            transition: width 0.3s ease;
            overflow: hidden;
        }

        .ui-draggable-handle {
            cursor: pointer;
        }

        .collapsed .content-wrapper {
            margin-left: 50px; /* điều chỉnh theo kích thước thu nhỏ */
        }

        .expanded .content-wrapper {
            margin-left: 250px; /* điều chỉnh theo kích thước mở rộng */
        }
    </style>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/Content/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Content/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/Content/dist/css/background_menu.css" />
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Content/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Content/plugins/summernote/summernote-bs4.min.css">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="@Url.Action("Logout","Users")" class="nav-link"><img height="32" width="32" src="~/Content/images/logout.png" /></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <img src="~/Content/images/full_screen.png" alt="iconf" />
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4 " style="background-color: white">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index","Admin")" class="brand-link background_menu" style="background-color: blanchedalmond">
                <img src="~/Content/images/lk.jpg" alt="Admin" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light" style="color: black; font-size:22px;">LK Website Admin</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar ">
                <!-- Sidebar Thông tin user (ảnh, tên) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex justify-content-center">
                    <div class="info text-center">
                        <img src="@Url.Action("GetImage", "Users", new { fullname = Session["fullname"] })" alt="Avatar" class="user-image" style="max-width: 200px; max-height: 200px;" />
                        <a style="color: black" href="#" class="d-block">@Session["fullname"]</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Users")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Tài khoản
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("Index","Subjects")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Môn học
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("Index","Quizzes")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Bài kiểm tra
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("Index","Questions")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Câu hỏi
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("Index","Score")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Điểm
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("Index","Documents")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Tài liệu PDF
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="@Url.Action("Index","Videos")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Video bài giảng
                                </p>
                            </a>
                        </li>
                        <br />
                        <button style="margin-top: 10px; font-size: 16px;" id="toggleButton">Thu nhỏ</button>
                        <!--
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Posts")" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Bài viết
                                </p>
                            </a>
                        </li>
                            -->
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="background-color:white">
            <!-- Main content -->
            <div style="margin-left: 100px; margin-right: 100px; margin-top: 50px; background-color:white">
                @RenderBody()
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>&copy; Thiết kể bởi LK Family.</strong>
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 2.0.0
            </div>
        </footer>
    </div>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(document).ready(function () {
            $('#toggleButton').click(function () {
                $('body').toggleClass('collapsed');
                adjustContentWidth(); // Thêm dòng này để điều chỉnh kích thước nội dung
            });

            // Kích thước khởi tạo của thanh sidebar (thu nhỏ)
            var initialWidth = 50;

            $('.main-sidebar').draggable({
                axis: 'x', // Chỉ di chuyển theo chiều ngang
                containment: [initialWidth, 0, window.innerWidth, window.innerHeight],
                drag: function (event, ui) {
                    var contentWidth = $(window).width() - ui.position.left;
                    $('.content-wrapper').css('margin-left', ui.position.left);
                },
                stop: function (event, ui) {
                    // Lưu giá trị của thanh sidebar sau khi dừng kéo
                    initialWidth = ui.position.left;
                }
            });

            // Thêm hàm để điều chỉnh kích thước nội dung
            function adjustContentWidth() {
                var contentWidth = $('body').hasClass('collapsed') ? 50 : 250;
                $('.content-wrapper').css('margin-left', contentWidth);
            }
        });
    </script>

    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Content/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Content/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Content/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/Content/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/Content/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Content/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Content/plugins/moment/moment.min.js"></script>
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Content/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/Content/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Content/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Content/dist/js/pages/dashboard.js"></script>
</body>
</html>